# Generated by Django 5.2.1 on 2025-05-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='auth_level',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.AlterField(
            model_name='users',
            name='regions',
            field=models.ManyToManyField(blank=True, through='usr.UserRegion', to='usr.region', verbose_name='Regiões'),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo')], default='ACTIVE', max_length=50, verbose_name='Status'),
        ),
    ]
